### ISSUE TITLE
Error in 'docker-composer up' command

### ISSUE THREAD

**Issue by robson-alcantara** [NearbyShops/Nearby-Shops-API#7]
When trying to run the system, it triggers the following error:

nbs_api_container | Admin Role updated : Row count : 1
nbs_api_container | Base URL : http://0.0.0.0:80
nbs_api_container | java.net.SocketTimeoutException: timeout
nbs_api_container | 	at okio.Okio$4.newTimeoutException(Okio.java:227)
nbs_api_container | 	at okio.AsyncTimeout.exit(AsyncTimeout.java:284)
nbs_api_container | 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:240)
nbs_api_container | 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
.
.
.

This is my 'docker-compose.yml' file:

version: '3.6'
services:
  nbs_api:
    image: nearbyshops/nearbyshops
    ports:
      - "8060:8060"
    container_name: nbs_api_container
    volumes:
      - db_data:/var/lib/postgresql/12/main
      - api_data:/root/nearbyshops/data
    restart: always
    entrypoint: ["/root/nbs.sh"]

volumes:
    db_data:
    api_data:

I'm try to running on 8060 port, but the system print this message: 'nbs_api_container | Base URL : http://0.0.0.0:80'

**Comment by SumeetMoray** [comment]
Dont change the internal port ... there is no need for it !
change the port to "8060:80" 

and try again !

**Comment by robson-alcantara** [comment]
I already have a server running on port 80, is there a problem?

**Comment by SumeetMoray** [comment]
you didnt read what i wrote ...  change the port to "8060:80" 

and run again !

**Comment by robson-alcantara** [comment]
I read what you wrote, but I had not informed you that I already had another service on port 80. Sorry for the lack of knowledge.

And continuing, it didn't work

**Comment by robson-alcantara** [comment]
The complete log

Starting nbs_api_container ... done
Attaching to nbs_api_container
nbs_api_container | Hello 
nbs_api_container | Today is Sat Apr 18 00:21:00 IST 2020
nbs_api_container | Starting Nearby Shops API Server
nbs_api_container |  * Starting PostgreSQL 12 database server
nbs_api_container |    ...done.
nbs_api_container | Apr 18, 2020 12:21:09 AM org.apache.commons.beanutils.FluentPropertyBeanIntrospector introspect
nbs_api_container | INFO: Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
nbs_api_container | Printing API Configuration :  
nbs_api_container | Base URI : http://0.0.0.0:80
nbs_api_container | Postgres Connection URL : jdbc:postgresql://localhost:5432/nearbyshopsdb
nbs_api_container | SMTP URL : smtp.mailgun.org
nbs_api_container | SMTP PORT : 587
nbs_api_container | SMTP USERNAME : postmaster@example.org
nbs_api_container | SMTP PASSWORD : abcde12345
nbs_api_container | Email Sender Name : Farmers Garden
nbs_api_container | Email Address : noreply@farmersgarden.org
nbs_api_container | Postgres Username : nearbyshops
nbs_api_container | Postgres Password : dailyneeds
nbs_api_container | MSG91_KEY : abcde12345
nbs_api_container | REFERRAL CREDIT FOR DRIVER REGISTRATION : 200
nbs_api_container | REFERRAL CREDIT FOR END USER REGISTRATION : 100
nbs_api_container | Joining Credit For End-User : 100
nbs_api_container | Joining Credit For Shop-Owner : 100
nbs_api_container | Token Duration Minutes : 1440
nbs_api_container | Email Verification Code Expiry Minutes : 10
nbs_api_container | Phone OTP Expiry Minutes : 10
nbs_api_container | Password Reset Code Expiry Minutes : 10
nbs_api_container | MAX LIMIT : 100
nbs_api_container | Tables Upgrade Complete ... !
nbs_api_container | Tables Created ... !
nbs_api_container | Admin Username : admin@nearbyshops.org |  Admin Password : password
nbs_api_container | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
nbs_api_container | SLF4J: Defaulting to no-operation (NOP) logger implementation
nbs_api_container | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
nbs_api_container | Admin Role updated : Row count : 1
nbs_api_container | Base URL : http://0.0.0.0:80
nbs_api_container | java.net.SocketTimeoutException: timeout
nbs_api_container | 	at okio.Okio$4.newTimeoutException(Okio.java:227)
nbs_api_container | 	at okio.AsyncTimeout.exit(AsyncTimeout.java:284)
nbs_api_container | 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:240)
nbs_api_container | 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
nbs_api_container | 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
nbs_api_container | 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
nbs_api_container | 	at okhttp3.internal.http1.Http1Codec.readResponse(Http1Codec.java:191)
nbs_api_container | 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:132)
nbs_api_container | 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:54)
nbs_api_container | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
nbs_api_container | 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
nbs_api_container | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
nbs_api_container | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
nbs_api_container | 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
nbs_api_container | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
nbs_api_container | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
nbs_api_container | 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
nbs_api_container | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
nbs_api_container | 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
nbs_api_container | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
nbs_api_container | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
nbs_api_container | 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
nbs_api_container | 	at okhttp3.RealCall.execute(RealCall.java:63)
nbs_api_container | 	at org.nearbyshops.Main.sendPing(Main.java:575)
nbs_api_container | 	at org.nearbyshops.Main$1.run(Main.java:537)
nbs_api_container | 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
nbs_api_container | 	at java.base/java.util.TimerThread.run(Timer.java:506)
nbs_api_container | Caused by: java.net.SocketException: Socket closed
nbs_api_container | 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:183)
nbs_api_container | 	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
nbs_api_container | 	at okio.Okio$2.read(Okio.java:138)
nbs_api_container | 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
nbs_api_container | 	... 24 more

**Comment by SumeetMoray** [comment]
its port 8060 not 80 ... so it should work even if other service is running on port 80 .. port 80 is internal port inside container. 

And other thing ... you can create a new server and try on another server. It takes only 5 $ per month to create a new server. 

We have limited people we cant give you support for this small port issue !

You can do google search and find solution to this issue !

**Comment by robson-alcantara** [comment]
Right. Thanks. I will find the solution and post here.
